### ISSUE TITLE
[Epic] Analytics

### ISSUE THREAD

**Issue by pmolina** [exactly/app#953]
- [x] Remove https://www.npmjs.com/package/@analytics/google-analytics and use the original.
- [ ] Tagging on every event (e.g.: "page view"). We have to set every tag on the global context.
- [x] ~[Arena analytics#947](https://github.com/exactly/app/issues/947)~
- [ ] Fully implement [Google Analytics 4 ecommerce module](https://developers.google.com/analytics/devguides/collection/ga4/ecommerce?client_type=gtag)
